webonnx/wonnx

.gitignore
examples/squeeze.rs

This allows `cargo run --release --example squeeze -- ./examples/data/images/pelican.jpeg` (the behaviour without specifying a path is unchanged)

Feature: accept image path squeeze

---

README.md
src/compiler.rs
src/optimisation.rs
src/sequencer.rs
tests/identity.rs

These ops appear to only change shape (which we don't care about as we require the dimensions to be inferred up front anyway), not data. Squeeze was already there so I added Unsqueeze and Identity as well.
We should probably not bother copying data between buffers but have a step in the compiler that simply aliases buffers, i.e.  in `input_a -> Identity -> SomeOtherOp`, the `SomeOtherOp` should just take `input_a` as input rather than the output from identity (which we then won't generate).

feat: support Unsqueeze and Identity ops

---

README.md
src/compiler.rs
tests/globalaveragepool.rs

GlobalAveragePool is basically a special case of the AveragePool op where kernel_size=image_size. This means that it simply averages all pixels in a channel (e.g. NxCxWxH becomes NxCx1x1).
This implementation just re-uses the AveragePool implementation. This implementation does not appear to work with output tensors with the total element count not divisible by 4 (see #32), but works fine otherwise.

feat: Implement GlobalAveragePool op

---

README.md
wonnx/src/resource.rs

Fix #50, it simply uses wgpu's functions to decide a GPU based on env variables.
In the future we should probably also add a way to construct a session with a specific wgpu device if the user wants to select a specific GPU.

feat: honor WGPU_ADAPTER_NAME and WGPU_BACKEND env variables

---

README.md
wonnx/src/compiler.rs
wonnx/templates/endomorphism/gather.wgsl
wonnx/templates/structs.wgsl
wonnx/tests/gather.rs

Implements the Gather operation, as used in e.g. BERTsquad. In a nutshell, this operator accepts a data tensor (typically f32) and an indexes tensor (typically i32), and produces a new tensor that has the elements at the specified indices from the data array. Using the 'axis' attribute it is possible to select indices from inner dimensions.
https://github.com/onnx/onnx/blob/main/docs/Operators.md#gather
Axis=0 case seems to work, need some more time to implement support for non-zero axis cases.

Implement Gather operation

---

README.md
wonnx/src/compiler.rs
wonnx/src/gpu.rs
wonnx/src/resource.rs
wonnx/src/utils.rs
wonnx/tests/arithmetic.rs
wonnx/tests/reduce.rs

WGSL does not appear to support 64-bit integers, so the best we can do (apart from building all sorts of complicated 64-bit logic based on 32 bit ints) is to use i32 instead (this also means: load i64 tensors as i32) and hope for the best (and wait for WGSL to start supporting 64 bit ints).
In practice it appears models use i64 but do not need the full range (i.e. in one of the ONNX files for BERTSQuAD, the input tokens are i64 tensors, but these values would also fit in i32).
Still need to implement the 64-to-32 conversion when loading tensors.

Process i64 data as i32 data

---

wonnx-cli/src/info.rs

The use of `HashMap` and `HashSet` made the output of `nnx info <model>` nondeterministic, which makes it hard to compare it between an unoptimized and optimized version of the same model. This PR switches the relevant data structures to their deterministic `BTree` variants to fix that.

Make `nnx info` deterministic

---

wonnx/tests/arithmetic.rs

tests: use weaker comparison in test_pow because WGSL's pow(x,y) appears very imprecise

---

wonnx-cli/src/gpu.rs
wonnx-cli/src/main.rs
wonnx-cli/src/types.rs
wonnx/src/ir.rs
wonnx/src/lib.rs

Currently, it is only possible to construct an inference session that infers all of a model's outputs. This is not always desired (e.g. some outputs may be unused). For debugging purposes it may be useful to be able to calculate the output of a specific (intermediate) node.
This patch allows users to optionally specify a set of output names. When specified, only those outputs will be calculated and returned. Due to the way our IR is constructed, this also means that intermediate nodes that are not necessary to calculate the specified outputs will not be processed.
This adds `Session::from_{path|bytes|model}_with_options` and a `SessionOptions` struct. We can add more options to this struct in the future (e.g. GPU selection and such). Users should probably always add in a …

feat: add a way to only partially execute a model by manually specifying output names

---

wonnx-cli/src/main.rs

This PR makes the CLI display friendly error messages:
````
Error: backend execution error: IR error: issue with data types: parametrized dimensions are not supported (this may be solved by running onnx-simplifier on the model first)
````
instead of the `Debug` ones:
````
Error: BackendExecutionFailed(GpuError(CompileError(InvalidInputShape { input_index: 1, input_shape: Shape { dims: [2, 768], data_type: F32 } })))
````

ux: show friendly error message in CLI instead of debug one

---

wonnx/src/resource.rs

Using `Backends::all()` enables unsupported backends such as OpenGL, which results in obscure errors at least on my Linux system.

Use only primary wgpu backends by default

---

wonnx/src/compiler.rs
wonnx/src/utils.rs

As far as I can tell, none of these asserts are in performance-sensitive code, so it makes sense to have them always checked to ensure that no invariants are violated.

Promote `debug_assert`s to normal `assert`s

---

wonnx/templates/endomorphism/map.wgsl

The `tanh` function in WGSL apparently produces NaN values for large (absolute) inputs. As `tanh` basically converges to 1, this PR clamps the input values to `tanh` to be between [-10, 10].
````python
>>> import math
>>> math.tanh(10)
0.9999999958776927
>>> math.tanh(-10)
-0.9999999958776927
````

fix: prevent tanh from producing NaN values

---

wonnx/src/compiler.rs

When doing a split of a `2x1x256` tensor into two `1x1x256` tensors I found that the second tensor was all zeroes. This was caused by the fact that the Split shader would only be started with `output_lengths[0]/256` workgroups (and hence would only copy 256 values from input) whereas there are in fact 512 values (so n_threads should be 2). This PR changes the number of threads to `input_lengths[0]/256` which makes this work properly.
Note we can't enable the ONNX backend tests for this op because those use dynamic inputs for the `split` input (which we don't support at the moment). The `test_split` case doesn't catch this error as the number of elements is below 256, and we simply start one thread (with workgroup size 256) in that case.

Fix: split operator does not take all elements into account

---

README.md

When looking at a crate's README, I usually look for the docs.rs badge at the top, and assume that it doesn't have docs otherwise. I thought that was initially the case with wonnx, but then I noticed the link to the docs later in the readme. Figured I'd add the badge to stop others from making the same assumption I did 👌

docs: add docs.rs badge to readme

---

wonnx/src/ir.rs

Hi,
rustc was previously accepting this incorrect code:
```rust
async fn test<'a>() { // `'a`, being a lifetime parameter, must be longer than the entire function body
let f = |_: &'a str| {}; // the argument is required to outlive `'a`
f(&String::new()); // an argument of shorter lifetime is passed!
}
```
This got fixed in the current beta 1.64, but [we found that wonnx relies on this bug](https://github.com/rust-lang/rust/issues/100544). This PR tries to fix this.

remove incorrect lifetime annotation

---

Cargo.lock
wonnx-cli/Cargo.toml
wonnx-preprocessing/Cargo.toml
wonnx/Cargo.toml
wonnx/src/gpu.rs

Due to https://github.com/gfx-rs/wgpu/issues/3105, multiple versions of wgpu in the same application aren't supported, so update to 0.14 (somehow, using multiple versions sometimes works on my system, but I don't want to unearth any eldritch horrors, so I haven't investigated why).
- In wgpu 0.14, https://github.com/gfx-rs/wgpu/pull/3023 fixes the validation of buffer usages, so they now behave like they do in WebGPU proper. This means we always have to go through an extra (non-storage) buffer when copying data back from the GPU.

Update to wgpu 0.14

---

wonnx-wasm/Cargo.toml

This is ignored, since the package is part of a containing workspace, and it makes Cargo print a warning every time you do something, so it's better to remove it.

Remove `profile.release` entry from wonnx-wasm

---

.github/workflows/create-py-mac.yaml
.github/workflows/create-py-manylinux.yaml
.github/workflows/create-py-windows.yaml
wonnx-py/Cargo.toml
wonnx-py/pyproject.toml

This pull request change the CD logic to publish on tag release to make it in sync with the rust publishing version

Publish `wonnx` on tag release

---

wonnx/src/gpu.rs

This way, the node type is mentioned if the node has no name, which can often pinpoint the specific node regardless

Improve `CompileError` message with unnamed nodes

---

wonnx-cli/src/cpu.rs
wonnx/src/compiler.rs
wonnx/src/gpu.rs
wonnx/src/ir.rs

This PR enabled re-usage of buffers for intermediate values (see #47) using a graph coloring algoritm. Basically, during the 'pre sequence' phase, a buffer manager keeps track of shared buffers and hands them out for use as intermediate value buffer, while keeping track of the lifetimes of each buffer. 
For the included MNIST example (which is basically a linear graph of 8 nodes, optimized down to 6 nodes), we'd previously allocate 6 buffers for intermediate values. With this PR, only 2 are allocated (leading to a reduction of 1.46x in total buffer size). For the Squeeze example, the difference is more dramatic (only 3 buffers needed, 3.19x improvement in size). This is due to the fact that Squeeze too is relatively linear, but with multiple similar blocks of nodes repeated.
Note, this PR …

perf: re-use intermediate value buffers

---

wonnx/src/compiler.rs
wonnx/src/optimizer.rs
wonnx/templates/snippets/activation_scalar.wgsl
wonnx/templates/snippets/activation_vec.wgsl
wonnx/tests/arithmetic.rs

This changes the input->attribute conversion to work with any element type, and passes the min and max attributes to the shader (which was expecting input buffers for some reason).
The upstream tests for this use dynamic min/max inputs and won't work with wonnx, so I've added a custom Rust test.

Fix `Clip` node implementation

---

wonnx/Cargo.toml
wonnx/src/compiler.rs
wonnx/src/optimizer.rs

Fixes https://github.com/webonnx/wonnx/issues/159
A better way to avoid issues like this would be to use a proper IR instead of the raw protobuf types, but that's a pretty major refactoring.
I didn't include a test here since the ONNX file in question is pretty large and still doesn't work because of other missing features.

Respect `raw_data` when promoting initializer

---

wonnx/src/compiler.rs
wonnx/templates/matrix/concat.wgsl
wonnx/tests/concat.rs

UNet caused errors because the Concat operator could not handle the large output sizes of some Concat operations.
The solution for this is to change the workgroup dimensions to also use the y dimension.
Since there is a limit of threads per dimension, this allows us quadratically increase the maximum possible output size.
Fixes #178.

Allow larger output sizes for Concat

---

Cargo.lock
wonnx/Cargo.toml
wonnx/src/compiler.rs
wonnx/src/lib.rs

`OnceLock` can be used to achieve the same thing without pulling in a dependency. Requires Rust 1.70.0.

Remove `lazy_static` dependency

---

wonnx/src/utils.rs

mention the field name in error message as well as the index of the parametrized dimension, so user can fix it

Improve `DataTypeError` message with `parametrized dimension`

---

wonnx/src/optimizer.rs

In the dependency upgrade for wgpu from 16 -> 19, wbgpu started properly labeling their structs as non send/sync which broke the expectations for the async_recursion proc macro. By configuring the macro to not expect a type that is Send, the wasm build of wgpu should properly compile. No callsites of the updaded function require that the type be Send, so there wasn't a need to update anything else.

set async_recursion to ?Send for wasm32 arch
